/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:aa2a0e01-90f5-43fb-a4f2-a2f714743736",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_8SHCmUxfF",
    "aws_user_pools_web_client_id": "75d1i6e99o148j5l6g0cv5t941",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cloud_logic_custom": [
        {
            "name": "minecraftserver",
            "endpoint": "https://tlfpnktpc5.execute-api.eu-central-1.amazonaws.com/staging",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
